# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: CopyFilesOverSSH@0
  displayName: 'Securely copy files to the remote machine'
  inputs:
    sshEndpoint: 'SSH chris@blog.acmattheis.de'

    sourceFolder: '$(build.artifactstagingdirectory)'

    targetFolder: stagevsts


- task: DownloadSecureFile@1
  displayName: 'Download secure file'
  inputs:
    secureFile: '235a203c-7c46-45fc-a211-ca4a0ef8817f'

- script: echo Hello, world!
  displayName: 'Run a one-line script'


- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo can I just add more lines here ?
    date -I
    uname -a
    pwd
    find .
    mount
  displayName: 'Run a multi-line script'
