# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    set -x
    set
    pwd
    uname -a
    # git submodule foreach -q --recursive 'branch="$(git config -f $toplevel/.gitmodules submodule.$name.branch)"; [ -z "$branch" ] && git checkout master || git checkout $branch'
    git submodule update --init --recursive
    echo hugo # This commands builds your website on travis
    cd ..
    pwd
    find .
  displayName: 'Run a multi-line script'

# Copy Files Over SSH
# Copy files or build artifacts to a remote machine over SSH
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'SSH chris@blog.acmattheis.de'
    #sourceFolder: # Optional
    #contents: '**' 
    targetFolder: /var/www/kuris4 # Optional
    cleanTargetFolder: false # Optional
    overwrite: true # Optional
    #failOnEmptySource: false # Optional
    #flattenFolders: false # Optional

- bash: |
   # Write your commands here
   
   # Use the environment variables input below to pass secret variables to this script
   pwd
   echo chmod 600 $DOWNLOADSECUREFILE_SECUREFILEPATH 
   echo ssh -o StrictHostKeyChecking=no -i $DOWNLOADSECUREFILE_SECUREFILEPATH  -l chris blog.acmattheis.de uname -a
  displayName: 'Bash Script'
