# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    set -x
    set
    pwd
    uname -a
    echo ===============
    git submodule update --init --recursive
    echo hugo # This commands builds your website on travis
    cd $BUILD_BINARIESDIRECTORY
    pwd
    curl -v -k -L -O https://github.com/gohugoio/hugo/releases/download/v0.51/hugo_0.51_Linux-64bit.deb
    sudo dpkg -i hugo_0.51_Linux-64bit.deb
    type hugo
    ls -ali
    cd $BUILD_SOURCESDIRECTORY
    hugo -d $BUILD_STAGINGDIRECTORY
    cd $BUILD_STAGINGDIRECTORY
    ls -ali
  displayName: 'Get and compile site'

# Copy Files Over SSH
# Copy files or build artifacts to a remote machine over SSH
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'key_cubox_chris'

- bash: |
   # Write your commands here
   set -x
   # Use the environment variables input below to pass secret variables to this script
   cd $BUILD_STAGINGDIRECTORY
   pwd
   chmod 600 $DOWNLOADSECUREFILE_SECUREFILEPATH 
   ssh -o StrictHostKeyChecking=no -i $DOWNLOADSECUREFILE_SECUREFILEPATH  -l chris blog.acmattheis.de uname -a
   # scp -v -o ConnectTimeout=90 -r -C  -i $DOWNLOADSECUREFILE_SECUREFILEPATH * chris@blog.acmattheis.de:/var/www/kuris2 # verbose is slow
   scp -o ConnectTimeout=90 -r -C  -i $DOWNLOADSECUREFILE_SECUREFILEPATH * chris@blog.acmattheis.de:/var/www/kuris2
  displayName: 'Data Deploy'
